// Response templates for formatting output
export interface ResponseTemplate {
  id: string;
  name: string;
  format: 'markdown' | 'json' | 'plain';
  template: string;
}

export const templatesConfig: Record<string, ResponseTemplate> = {
  // Success response template
  'webhook-success': {
    id: 'webhook-success',
    name: 'Webhook Success Response',
    format: 'json',
    template: JSON.stringify(
      {
        status: 'success',
        message: '{{message}}',
        issueId: '{{issueId}}',
        action: '{{action}}',
        timestamp: '{{timestamp}}',
      },
      null,
      2,
    ),
  },

  // Error response template
  'webhook-error': {
    id: 'webhook-error',
    name: 'Webhook Error Response',
    format: 'json',
    template: JSON.stringify(
      {
        status: 'error',
        error: '{{error}}',
        code: '{{code}}',
        timestamp: '{{timestamp}}',
      },
      null,
      2,
    ),
  },

  // Copilot result template
  'copilot-result': {
    id: 'copilot-result',
    name: 'Copilot CLI Result',
    format: 'markdown',
    template: `## Copilot Analysis Result

### Issue: {{title}}

**Agent:** {{agentName}}
**Processed at:** {{timestamp}}

---

### Analysis

{{analysis}}

---

### Recommended Actions

{{recommendations}}

---

*Generated by Coplie - Linear + Copilot CLI Integration*`,
  },

  // Linear comment template
  'linear-comment': {
    id: 'linear-comment',
    name: 'Linear Comment Template',
    format: 'markdown',
    template: `### 🤖 Copilot Analysis

{{analysis}}

---

**Agent:** {{agentName}}
**Processed:** {{timestamp}}`,
  },

  // Summary report template
  'summary-report': {
    id: 'summary-report',
    name: 'Summary Report',
    format: 'markdown',
    template: `# Issue Processing Summary

## Overview
- **Total Issues Processed:** {{totalProcessed}}
- **Successful:** {{successful}}
- **Failed:** {{failed}}
- **Period:** {{startDate}} to {{endDate}}

## Details

{{details}}

---

*Report generated at {{timestamp}}*`,
  },
};

// Render a response template with variables
export function renderTemplate(templateId: string, variables: Record<string, string | number | undefined>): string {
  const template = templatesConfig[templateId];
  if (!template) {
    throw new Error(`Template not found: ${templateId}`);
  }

  let rendered = template.template;

  // Replace variables
  for (const [key, value] of Object.entries(variables)) {
    const placeholder = `{{${key}}}`;
    rendered = rendered.replaceAll(placeholder, String(value ?? ''));
  }

  return rendered;
}

// Parse template format
export function getTemplateFormat(templateId: string): 'markdown' | 'json' | 'plain' {
  return templatesConfig[templateId]?.format || 'plain';
}
